spring.application.name=zzonggeut
server.port=9090

# MySQL 연결
spring.datasource.url=jdbc:mysql://localhost:3306/zzonggeut_db?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf 캐시 끄기 (개발 중 실시간 반영)
spring.thymeleaf.cache=false